# Generated by Django 4.1.2 on 2023-07-07 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id_artista', models.AutoField(db_column='idArtista', primary_key=True, serialize=False)),
                ('artista', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('concepto', models.CharField(max_length=50)),
                ('tecnica', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=500)),
                ('imagen', models.ImageField(null=True, upload_to='ground_zero')),
                ('id_artista', models.ForeignKey(db_column='idArtista', on_delete=django.db.models.deletion.CASCADE, to='ground_zero.artista')),
            ],
        ),
    ]
